### ISSUE TITLE
Keeps stopping

### ISSUE THREAD

**Issue by ghost** [haridhayal11/treble_proton_aosp#6]
Steps to reproduce the problem.

1. Fresh install.
2. First boot.
3. Restart device.
4. Settings keeps stopping... Phone and Messaging Storage keeps stopping... etc.

?

**Comment by haridhayal11** [comment]
Try using a permissive kernel or flash permissiver.zip (found in telegram group)

**Comment by ghost** [comment]
Thank you, but I don't want to change `SELinux` to `Permissive` for security reasons.

This isn't a feature request, is there any possibility to make the ROM works without it?

Still, thanks for bringing the ROM.
