### ISSUE TITLE
Graphene sandbox service not working.

### ISSUE THREAD

**Issue by rajshekhar99** [haridhayal11/treble_proton_aosp#8]
Failing at syncing metadata. 
Error prompt: sync failed due to security error server responded with unexpected http code. Phone was rooted in last rom, but this flash unrooted the phone. So i can't thinkg why it's failing to sync or am i missing something.

build: [proton-12.4.1-phh-v415-arm64_bvN.img.xz](https://github.com/haridhayal11/treble_proton_aosp/releases/download/v415-21-08-2022/proton-12.4.1-phh-v415-arm64_bvN.img.xz)

I tried formatting, reflashing but it's not working.  It would be great if it can work, so google services can be installed since my phone doesn't have custom recovery, and this build has good improvement over phusson treble builds. 

thanks in advance for build

**Comment by haridhayal11** [comment]
The builds are End-of-Life now. Sorry
